apiVersion: v1
kind: Pod
metadata:
  name: k8s-dashboard
spec:
  container:
  - name: k8s-dashboard
    image: k8s-dashboard
  serviceAccount: dashboard-sa         # uses this serviceaccount for the pod
  automountServiceAccountToken: false  # prevents the pod from mounting a service account 
