apiVersion: v1
kind: Pod
metadata:
  name: config-map-pod
  labels:
    name: config-map-pod
spec:
  container:
  - name: config-map-pod
    image: config-map-image
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: app-config
