apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: ["sleep2.0"]
    args: ["10"]
    ports:
    env:
      - name: APP_COLOR
        value: pink
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef:
      - name: APP_COLOR
        valueFrom:
          secretKeyRef:
