apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secret-pod
spec:
  container:
  - name: secret-pod
    image: secret-image
    ports:
      - containerPort: 8080
    envFrom:    # all env
      - secretRef:
          name: app-secret
    env:        # single envs 
      - name: password
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: password
  volumes:
  - name: app-secret-volume
    secret:
      secretName: app-secret
